[versions]
jetbrains-annotations = "26.0.2"
asm = "9.7.1"
download_task = "5.6.0"
gson = "2.11.0"
quilt-json5 = "1.0.3"
mappingio = "0.7.1"
stitch = "0.6.2"
tinyremapper = "0.11.0"
enigma = "2.5.2"
vineflower = "1.10.1"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
download_task = { module = "de.undercouch:gradle-download-task", version.ref = "download_task" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
quilt-json5 = { module = "org.quiltmc:quilt-json5", version.ref = "quilt-json5" }
mappingio = { module = "net.fabricmc:mapping-io", version.ref = "mappingio" }
stitch = { module = "net.fabricmc:stitch", version.ref = "stitch" }
tinyremapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tinyremapper" }
enigma = { module = "cuchaz:enigma", version.ref = "enigma" }
enigma-cli = { module = "cuchaz:enigma-cli", version.ref = "enigma" }
enigma-gui = { module = "cuchaz:enigma-swing", version.ref = "enigma" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
